In [187]:
#Name: SAVALIYA UTTAM PANKAJBHAI
#Registration Number: 25BAS10005
#Course: Fundamentals of AI and ML

In [ ]:
import pandas as pd

In [136]:
df = pd.read_csv("synthetic_health_data.csv")

In [137]:
df

,age,diet,exercise_days,sleep_hours,stress,bmi,smoking,alcohol,family_history,risk_level
0,56,Poor,3,4,High,19.9,No,High,Yes,High
1,69,Average,2,5,High,33.9,No,Low,Yes,High
2,46,Average,7,12,Medium,31.0,Yes,Low,Yes,Medium
3,32,Good,1,11,High,38.1,No,High,No,Medium
4,60,Good,6,11,Low,34.6,No,Low,Yes,Medium
...,...,...,...,...,...,...,...,...,...,...
3995,35,Poor,7,7,Low,16.6,No,Low,Yes,Low
3996,22,Average,6,8,Medium,38.8,No,Low,Yes,Low
3997,20,Poor,5,8,Low,30.3,No,Medium,Yes,Medium
3998,40,Poor,2,3,Low,35.0,No,Low,Yes,Medium
3999,43,Average,7,11,Medium,25.2,Yes,Medium,Yes,Low

In [138]:
df.shape

(4000, 10)

In [139]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             4000 non-null   int64
 1   diet            4000 non-null   object
 2   exercise_days   4000 non-null   int64
 3   sleep_hours     4000 non-null   int64
 4   stress          4000 non-null   object
 5   bmi             4000 non-null   float64
 6   smoking         4000 non-null   object
 7   alcohol         4000 non-null   object
 8   family_history  4000 non-null   object
 9   risk_level      4000 non-null   object
dtypes: float64(1), int64(3), object(6)
memory usage: 312.6+ KB

In [140]:
df.isna().sum()

age               0
diet              0
exercise_days     0
sleep_hours       0
stress            0
bmi               0
smoking           0
alcohol           0
family_history    0
risk_level        0
dtype: int64

In [141]:
df.duplicated().sum()

np.int64(0)

In [142]:
df.head()

,age,diet,exercise_days,sleep_hours,stress,bmi,smoking,alcohol,family_history,risk_level
0,56,Poor,3,4,High,19.9,No,High,Yes,High
1,69,Average,2,5,High,33.9,No,Low,Yes,High
2,46,Average,7,12,Medium,31.0,Yes,Low,Yes,Medium
3,32,Good,1,11,High,38.1,No,High,No,Medium
4,60,Good,6,11,Low,34.6,No,Low,Yes,Medium

In [143]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             4000 non-null   int64
 1   diet            4000 non-null   object
 2   exercise_days   4000 non-null   int64
 3   sleep_hours     4000 non-null   int64
 4   stress          4000 non-null   object
 5   bmi             4000 non-null   float64
 6   smoking         4000 non-null   object
 7   alcohol         4000 non-null   object
 8   family_history  4000 non-null   object
 9   risk_level      4000 non-null   object
dtypes: float64(1), int64(3), object(6)
memory usage: 312.6+ KB

In [144]:
df['age'].max()

80

In [145]:
df['age'].min()

18

In [146]:
df['diet'].value_counts()

diet
Average    1987
Poor       1216
Good        797
Name: count, dtype: int64

In [147]:
df['exercise_days'].max()

7

In [148]:
df['exercise_days'].min()

0

In [149]:
df['sleep_hours'].max()

12

In [150]:
df['sleep_hours'].min()

3

In [151]:
categorical_col=['diet','stress','smoking','alcohol','family_history','risk_level']

In [152]:
from sklearn.preprocessing import LabelEncoder

In [153]:
encoder={}

In [154]:
for i in categorical_col:
    le = LabelEncoder()
    df[i]=le.fit_transform(df[i])
    encoder[i]=le

In [155]:
df.head()

,age,diet,exercise_days,sleep_hours,stress,bmi,smoking,alcohol,family_history,risk_level
0,56,2,3,4,0,19.9,0,0,1,0
1,69,0,2,5,0,33.9,0,1,1,0
2,46,0,7,12,2,31.0,1,1,1,2
3,32,1,1,11,0,38.1,0,0,0,2
4,60,1,6,11,1,34.6,0,1,1,2

In [156]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             4000 non-null   int64
 1   diet            4000 non-null   int64
 2   exercise_days   4000 non-null   int64
 3   sleep_hours     4000 non-null   int64
 4   stress          4000 non-null   int64
 5   bmi             4000 non-null   float64
 6   smoking         4000 non-null   int64
 7   alcohol         4000 non-null   int64
 8   family_history  4000 non-null   int64
 9   risk_level      4000 non-null   int64
dtypes: float64(1), int64(9)
memory usage: 312.6 KB

In [157]:
from sklearn.model_selection import train_test_split

In [158]:
x=df.drop(columns='risk_level')
y=df['risk_level']

In [159]:
print(x.columns)

Index(['age', 'diet', 'exercise_days', 'sleep_hours', 'stress', 'bmi',
       'smoking', 'alcohol', 'family_history'],
      dtype='object')

In [160]:
print(y.name)

risk_level

In [161]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=42)

In [162]:
#from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

In [163]:
#model = LogisticRegression()
model = RandomForestClassifier(n_estimators=100,random_state=42)

In [164]:
model.fit(x_train,y_train)

RandomForestClassifier(random_state=42)

In [165]:
from sklearn.metrics import accuracy_score

In [166]:
y_pred = model.predict(x_test)

In [167]:
acc = accuracy_score(y_pred,y_test)

In [ ]:
print("Accuracy Score",acc)

Accuracy Score 0.96375

In [ ]:
df.head()

,age,diet,exercise_days,sleep_hours,stress,bmi,smoking,alcohol,family_history,risk_level
0,56,2,3,4,0,19.9,0,0,1,0
1,69,0,2,5,0,33.9,0,1,1,0
2,46,0,7,12,2,31.0,1,1,1,2
3,32,1,1,11,0,38.1,0,0,0,2
4,60,1,6,11,1,34.6,0,1,1,2

In [ ]:
model.predict([[56,2,3,4,0,19.9,0,0,1]])

c:\Users\jayga\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

array([0])

In [ ]:
import pickle

In [176]:
pickle.dump(model,open("notebook.pkl","wb"))

In [180]:
with open("label_encoders.pkl","wb") as f:
    pickle.dump(encoders,f)

In [186]:
from sklearn.preprocessing import LabelEncoder
import pickle

encoders = {}

for col in df.select_dtypes(include='object').columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    encoders[col] = le


with open("label_encoders.pkl", "wb") as f:
    pickle.dump(encoders, f)

In [185]:
print(encoders.keys())

dict_keys([])